### ISSUE TITLE
User can see others Groups

### ISSUE THREAD

**Issue by AMotaPT** [immense/Remotely#578] opened 2023-02-01 13:26 UTC
First all, great project. I love it.

I detected that even just choosing a group the user can view the remaining groups and equipment. It is not possible to access it remotely but it is possible for the user to change the equipment group and thus put it in his group and control it.

The user should only view his group and nothing else.

Version: 2023.01.20.0732

Best Regards

**Comment by lucent-sea** [comment] 2023-02-03 01:25
A little background.  If the device group has no other users, this was by design.  It was meant to prevent users from locking themselves out of devices, back when they were able to create groups.  This should have been changed when the device groups logic changed (during the migration to Blazor).

It should be fixed in the latest version.  I was able to repro the issue, and this fixed it.  If it didn't fix it for you, please post the repro steps, and I'll re-open this.

**Closed by lucent-sea** 2023-02-03 01:25 UTC

**Comment by AMotaPT** [comment] 2023-02-03 10:56
@lucent-sea 
The new update works, thank you much for your work and project.
