### ISSUE TITLE
Ubuntu Resident Agents did not work

### ISSUE THREAD

**Issue by abenchaaben** [immense/Remotely#637] opened 2023-05-17 14:52 UTC
**Describe the bug**
Hi, I installed Remotely using docker compose in my Ubuntu 22.04 machine. The idea is to be able to connect to this specific machine from inside and outside my network. To facilitate this for me, I installed the [Ubuntu x64 Bash Installer] Resident Agents. Everything went well and i don't have any error. I did not see any GUI that i can used to configure the connection, but i guess maybe I don't need one. Now, when i tried to connect to my machine from another one inside my network, it did not work and i have a error message "Session failed to start" even if I can see my machine information. When I tried the remote control option with ID, it did work. What i'm messing here?

**Additional Context**

**Comment by lucent-sea** [comment] 2023-05-18 02:34
Duplicate of #634

**Closed by lucent-sea** 2023-05-18 02:34 UTC
